### ISSUE TITLE
Maybe a readme and some documentation?

### ISSUE THREAD

**Issue by nathanielcook** [Clancey/SimpleDatabase#1]
I saw InstantDatabase mentioned [here](http://www.valentinpolushkin.com/data-storage-options-for-xamarin-apps) but I don't understand what it does. A short readme would be wonderful.

**Comment by Clancey** [comment]
I agree, I need to add a readme. Super quick overview:

Add a couple of extra attributes to your models, and it gives you a view model with the same interface as a TableViewSource, or ListViewAdapter while taking care of virtualizations and proper indexing. The sample shows it in action.
